### PR TITLE
Improve Message() and MessageSet() objects to better match the API specs and fix imports

### PR DESCRIPTION
**Pull request by edonosotti**
- [FIX] some imports were not working correctly when running unit tests from the repository root
- [IMPROVEMENT] expose all API "/message" properties in Message object
- [IMPROVEMENT] expose all Message object properties in MessageSet.new_message() method
- [IMPROVEMENT] add MessageSet.append_message() method
- update README files to reflect changes

### CODE REVIEW

**Review by ramovsky — APPROVED** [review]
This one is better than mine #2

**Comment by edonosotti** [comment]
Glad you liked it ;)

**Comment by ramovsky** [comment]
@edonosotti Even the changes are backward compatible, minor version bump will be a good idea.

**Review by nori0990 — APPROVED** [review]

**Comment by cristiancavalli** [comment]
@edonosotti Thanks for the contributions!

**Pull request merged**
