### PR TITLE
Fix absolute imports to support Python 3

### PR DESCRIPTION
**Pull request by noamelf**

### CODE REVIEW

**Review by stasfilin — APPROVED** [review]

**Comment by mukund-murali** [comment]
@noamelf Hey, can you sign the CLA so that this PR is merged?

**Comment by noamelf** [comment]
I signed it

**Comment by rrmerugu** [comment]
when are you guys planning to merge this ?

**Comment by cristiancavalli** [comment]
@noamelf Sorry for the delay -- thanks for the pr!!

**Pull request merged**
